export enum EntityType {
  AMOUNT = "AMOUNT",
  CATEGORY = "CATEGORY",
  MERCHANT = "MERCHANT",
  DATE = "DATE",
  CURRENCY = "CURRENCY",
  FREQUENCY = "FREQUENCY",
  GOALNAME = "GOALNAME",
  TARGETAMOUNT = "TARGETAMOUNT",
  TARGETDATE = "TARGETDATE",
  ASSETTYPE = "ASSETTYPE",
  ASSETNAME = "ASSETNAME",
  VALUE = "VALUE",
  PURCHASEDATE = "PURCHASEDATE",
  LIABILITYTYPE = "LIABILITYTYPE",
  ITEMNAME = "ITEMNAME",
  INTERESTRATE = "INTERESTRATE",
  LIMIT_ACTION = "LIMIT_ACTION",
  SALARY_ACTION = "SALARY_ACTION",
  SPEND_ACTION = "SPEND_ACTION",
  SOURCE = "SOURCE"
}

export const ENTITY_TYPE_LIST = Object.values(EntityType) as EntityType[];
