export enum Intent {
  ADD_INCOME = "ADD_INCOME",
  ADD_EXPENSE = "ADD_EXPENSE",
  INCOME_DECLARATION = "INCOME_DECLARATION",
  ADD_ASSET = "ADD_ASSET",
  ADD_LIABILITY = "ADD_LIABILITY",
  REFUND = "REFUND",
  AFFORDABILITY_CHECK = "AFFORDABILITY_CHECK",
  DEBT_FREEDOM_ANALYSIS = "DEBT_FREEDOM_ANALYSIS",
  SIP_VS_PREPAY = "SIP_VS_PREPAY",
  LOAN_ANALYSIS = "LOAN_ANALYSIS",
  GOAL_PLANNING = "GOAL_PLANNING",
  BUDGET_PLANNING = "BUDGET_PLANNING",
  SPENDING_ANALYSIS = "SPENDING_ANALYSIS",
  NET_WORTH_CHECK = "NET_WORTH_CHECK",
  CASHFLOW_WARNING = "CASHFLOW_WARNING",
  SAVINGS_INSIGHTS = "SAVINGS_INSIGHTS"
}

export const INTENT_LIST = Object.values(Intent) as Intent[];
